import posion from '../img/posion.png';
import posion2 from '../img/potion-posion.png';
import healthy from '../img/potion-healthy.png';
import magic from '../img/potion-magic.png';
import stamina from '../img/potion-stamina.png';



const recipe = [
    {recipe: 'Пшеница-Сердце даэдра',
    name: 'ЗЕЛЬЕ ВОССТАНОВЛЕНИЯ ЗДОРОВЬЯ',
    img: {healthy},
    key: 1},
    {recipe: 'Жир тролля-Лютый гриб',
    name: 'ЗЕЛЬЕ БЕШЕНСТВА',
    img: {posion2},
    key: 2},
    {recipe: 'Жир тролля-Паслён',
    name: 'ЗЕЛЬЕ УРОНА ЗДОРОВЬЮ',
    img: {posion},
    key: 3},
    {recipe: 'Жир тролля-Корень Нирна',
    name: 'ЗЕЛЬЕ УРОНА ЗДОРОВЬЮ',
    img: {posion},
    key: 4},
    {recipe: 'Жир тролля-Корень жарницы',
    name: 'ЗЕЛЬЕ УРОНА ЗДОРОВЬЮ',
    img: {posion},
    key: 5},
    {recipe: 'Корень Нирна-Ядовитый цветок',
    name: 'ЗЕЛЬЕ УРОНА ЗДОРОВЬЮ',
    img: {posion},
    key: 6},
    {recipe: 'Корень жарницы-Ядовитый цветок',
    name: 'ЗЕЛЬЕ УРОНА ЗДОРОВЬЮ',
    img: {posion},
    key: 7},
    {recipe: 'Жир тролля-Ядовитый цветок',
    name: 'ЗЕЛЬЕ УРОНА ЗДОРОВЬЮ',
    img: {posion},
    key: 8},
    {recipe: 'Лютый гриб-Пшеница',
    name: 'ЗЕЛЬЕ ВОССТАНОВЛЕНИЯ ЗДОРОВЬЯ',
    img: {healthy},
    key: 9},
    {recipe: 'Лютый гриб-Сердце даэдра',
    name: 'ЗЕЛЬЕ ВОССТАНОВЛЕНИЯ ЗДОРОВЬЯ',
    img: {healthy},
    key: 10},
    {recipe: 'Корень Нирна-Лютый гриб',
    name: 'ЗЕЛЬЕ УРОНА ЗАПАСУ СИЛ',
    img: {stamina},
    key: 11},
    {recipe: 'Корень жарницы-Корень Нирна',
    name: 'ЗЕЛЬЕ УРОНА ЗАПАСУ СИЛ',
    img: {stamina},
    key: 12},
    {recipe: 'Корень жарницы-Лютый гриб',
    name: 'ЗЕЛЬЕ УРОНА ЗАПАСУ СИЛ',
    img: {stamina},
    key: 13},
    {recipe: 'Гниль Намиры-Сердце даэдра',
    name: 'ЗЕЛЬЕ СТРАХА',
    img: {posion},
    key: 14},
    {recipe: 'Гниль Намиры-Ядовитый цветок',
    name: 'ЗЕЛЬЕ СТРАХА',
    img: {posion},
    key: 15},
    {recipe: 'Сердце даэдра-Ядовитый цветок',
    name: 'ЗЕЛЬЕ СТРАХА',
    img: {posion},
    key: 16},
    {recipe: 'Гниль Намиры-Корень жарницы',
    name: 'ЗЕЛЬЕ УРОНА МАГИИ',
    img: {magic},
    key: 17},
    {recipe: 'Корень жарницы-Сердце даэдра',
    name: 'ЗЕЛЬЕ УРОНА МАГИИ',
    img: {magic},
    key: 18},
    {recipe: 'Гниль Намиры-Сердце даэдра',
    name: 'ЗЕЛЬЕ УРОНА МАГИИ',
    img: {magic},
    key: 19}
]
export default recipe
