import posion from '../img/posion.png';
import power from '../img/potion-power.png';
import healthy from '../img/potion-healthy.png';
import magic from '../img/potion-magic.png';
import stamina from '../img/potion-stamina.png';



const recipe = [
    {recipe: 'Пшеница-Сердце даэдра',
    name: 'ЗЕЛЬЕ ВОССТАНОВЛЕНИЯ ЗДОРОВЬЯ',
    img: {healthy},
    key: 1},
    {recipe: 'Жир тролля-Лютый гриб',
    name: 'ЗЕЛЬЕ БЕШЕНСТВА',
    img: {power},
    key: 2},
    {recipe: 'Жир тролля-Паслён',
    name: 'ЗЕЛЬЕ УРОНА ЗДОРОВЬЮ',
    img: {posion},
    key: 3},
    {recipe: 'Корень Нирна-Паслён',
    name: 'ЗЕЛЬЕ УРОНА ЗДОРОВЬЮ',
    img: {posion},
    key: 4},
    {recipe: 'Жир тролля-Корень Нирна',
    name: 'ЗЕЛЬЕ УРОНА ЗДОРОВЬЮ',
    img: {posion},
    key: 5},
    {recipe: 'Жир тролля-Корень жарницы',
    name: 'ЗЕЛЬЕ УРОНА ЗДОРОВЬЮ',
    img: {posion},
    key: 6},
    {recipe: 'Корень Нирна-Ядовитый цветок',
    name: 'ЗЕЛЬЕ УРОНА ЗДОРОВЬЮ',
    img: {posion},
    key: 7},
    {recipe: 'Корень жарницы-Ядовитый цветок',
    name: 'ЗЕЛЬЕ УРОНА ЗДОРОВЬЮ',
    img: {posion},
    key: 8},
    {recipe: 'Жир тролля-Ядовитый цветок',
    name: 'ЗЕЛЬЕ УРОНА ЗДОРОВЬЮ',
    img: {posion},
    key: 8},
    {recipe: 'Лютый гриб-Пшеница',
    name: 'ЗЕЛЬЕ ВОССТАНОВЛЕНИЯ ЗДОРОВЬЯ',
    img: {healthy},
    key: 6},
    {recipe: 'Лютый гриб-Сердце даэдра',
    name: 'ЗЕЛЬЕ ВОССТАНОВЛЕНИЯ ЗДОРОВЬЯ',
    img: {healthy},
    key: 7},
    {recipe: 'Корень Нирна-Лютый гриб',
    name: 'ЗЕЛЬЕ УРОНА ЗАПАСУ СИЛ',
    img: {stamina},
    key: 8},
    {recipe: 'Корень жарницы-Корень Нирна',
    name: 'ЗЕЛЬЕ УРОНА ЗАПАСУ СИЛ',
    img: {stamina},
    key: 6},
    {recipe: 'Корень жарницы-Лютый гриб',
    name: 'ЗЕЛЬЕ УРОНА ЗАПАСУ СИЛ',
    img: {stamina},
    key: 7},
    {recipe: 'Гниль Намиры-Сердце даэдра',
    name: 'ЗЕЛЬЕ СТРАХА',
    img: {posion},
    key: 8},
    {recipe: 'Гниль Намиры-Ядовитый цветок',
    name: 'ЗЕЛЬЕ СТРАХА',
    img: {posion},
    key: 8},
    {recipe: 'Ядовитый цветок-Сердце даэдра',
    name: 'ЗЕЛЬЕ СТРАХА',
    img: {posion},
    key: 8},
    {recipe: 'Гниль Намиры-Корень жарницы',
    name: 'ЗЕЛЬЕ УРОНА МАГИИ',
    img: {magic},
    key: 6},
    {recipe: 'Корень жарницы-Сердце даэдра',
    name: 'ЗЕЛЬЕ УРОНА МАГИИ',
    img: {magic},
    key: 7},
    {recipe: 'Гниль Намиры-Сердце даэдра',
    name: 'ЗЕЛЬЕ УРОНА МАГИИ',
    img: {magic},
    key: 8}
]
export default recipe